= Azure AI 
:toc: manual

== Labs

[cols="5a,5a"]
|===
|Item | Note

|link:language/README.adoc[Azure AI Language]
|
* Recognize core concepts
* Comprehend information at a glance
* Analyze customer sentiment
* Process unstructured medical data
* Build conversational experiences
* Respond to customer queries
* Automatically categorize text
* Extract key phrases and concepts

|link:vision/README.adoc[Azure AI Vision]
|
* The Azure AI Vision service gives you access to advanced algorithms that process images and return information based on the visual features you're interested in. 

|link:vision/face/README.adoc[Azure AI Vision Face]
|
* The Azure AI Face service provides AI algorithms that detect, recognize, and analyze human faces in images.
* Facial recognition software is important in many scenarios, such as identification, touchless access control, and automatic face blurring for privacy.

|link:ai-custom-vision/README.adoc[AI Custom Vision Classification]
|
* Easily customize your own state-of-the-art computer vision models for your unique use case.
* https://azure.microsoft.com/en-us/products/ai-services/ai-custom-vision

|link:ai-custom-vision/README.adoc[AI Custom Vision Object Detection]
|
* To identify and locate specific objects within an image, providing both the object class and its location.

|link:ml-workspaces/README.adoc[ML Workspace]
|
* A workspace is the top-level resource that provides a centralized place to work with all the artifacts created when using Azure Machine Learning, including models, environments, components, and data assets. 

|link:autoML/README.adoc[Automated ML]
|
* Automated machine learning (AutoML) is the process of automating the time-consuming, iterative tasks of machine learning model development. It allows data scientists, analysts, and developers to build ML models with high scale, efficiency, and productivity all while sustaining model quality. 
* AutoML in Azure Machine Learning is based on a breakthrough from the Microsoft Research division.

|link:regression/README.adoc[Regission Model]
|A source code for demonstrate the regression.

|link:classification/README.adoc[Classificaton Model]
|

|link:clustering/README.adoc[Clustering Model]
|
|===

== Glosary

[cols="2,5a"]
|===
|Name |Note

|Resource Group
|
* Resource Group in Azure is to act as a container that holds related resources for an Azure solution. 
* Resource groups can include all the resources for the solution or only those resources that you want to manage as a group. You decide how you want to allocate resources to resource groups based on what makes the most sense for your organization.

|Workspaces
|A workspace provides a centralized place to keep track of all the artifacts you create while performing machine learning experiments.

|Azure AI Bot Service
|Azure AI Bot Service provide a platform for conversational artificial intelligence (AI), which designates the ability of software agents to participate in a conversation. 

|AI Hub
|
* An AI hub provides a collaborative workspace for AI solution development and management. 
* An Azure AI hub can host one or more projects. Each project encapsulates the tools and assets used to create a specific AI solution.
* An Azure AI hub is the foundation for AI development projects on Azure, and enables you to define shared assets that can be used across multiple projects. 

|===

== Responsible AI Principles

[cols="2,5a"]
|===
|Name |Note

|Fairness
|AI systems should treat all people fairly. 

Examples:

* Artificial intelligence (AI) system to support the process of accepting or rejecting mortgage applications, the *ethnicity* and *gender* should be considered to avoid biased decision making.
* The *fairness* involves evaluating and mitigating the bias introduced by the features of a model.

|Reliability and safety
|AI systems should perform reliably and safely. 

Examples:

* The *reliability and safety* is important for developing driverless agriculture vehicles to help harvest crops, that the vehicles will be deployed alongside people working in the crop fields, and as such, the company will need to carry out robust testing.

|Privacy and security
|AI systems should be secure and respect privacy. 

Examples:

* The *accountability* and *privacy and security* principles are most important when designing an AI system to manage healthcare data.

|Inclusiveness
|
* AI systems should empower everyone and engage people.
* AI should bring benefits to all parts of society, regardless of physical ability, gender, sexual orientation, ethnicity, or other factors.

|Transparency
|
* AI systems should be understandable. 
* Users should be made fully aware of the purpose of the system, how it works, and what limitations may be expected.

|Accountability
|
People should be accountable for AI systems. Designers and developers of AI-based solutions should work within a framework of governance and organizational principles that ensure the solution meets ethical and legal standards that are clearly defined.

Examples:

* Artificial intelligence (AI) defines the framework of governance and organization principles that meet ethical and legal standards of AI solutions
* The *accountability* and *privacy and security* principles are most important when designing an AI system to manage healthcare data.

|===


