= Azure AI Language

== Run the code

[source, bash]
----
$ python text-analysis.py 

-----Sentiment Analysis-----
The sentence to analyze: ['我3月12日在这家餐厅吃饭，只能说一句：哇！食物太棒了，我99%会再来一次！']
Sentiment: positive
Confidence: {'positive': 0.98, 'neutral': 0.01, 'negative': 0.01}
----------


-----Key Phrases-----
The sentence to analyze:  ['我3月12日在这家餐厅吃饭，只能说一句：哇！食物太棒了，我99%会再来一次！']
Key Phrases: ['我3月', '日', '这家餐厅吃', '食物', '会']
----------


-----Entities-----
The sentence to analyze:  ['我3月12日在这家餐厅吃饭，只能说一句：哇！食物太棒了，我99%会再来一次！']
Entity: 3月12日在                          Category: DateTime         Confidence: 0.98
Entity: 餐厅                              Category: Location         Confidence: 0.69
Entity: 99%                             Category: Quantity         Confidence: 1.0 
----------

-----Sentiment Analysis-----
The sentence to analyze: ['我5月17日来这里吃饭，体验很糟糕。食物上来时是冷的，服务员态度也不太好，我根本不喜欢这里。我不会再来了。']
Sentiment: negative
Confidence: {'positive': 0.0, 'neutral': 0.08, 'negative': 0.91}
----------


-----Key Phrases-----
The sentence to analyze:  ['我5月17日来这里吃饭，体验很糟糕。食物上来时是冷的，服务员态度也不太好，我根本不喜欢这里。我不会再来了。']
Key Phrases: ['我5月', '日', '里吃', '食物', '务', '态度也不太好', '根本不', '我不会']
----------


-----Entities-----
The sentence to analyze:  ['我5月17日来这里吃饭，体验很糟糕。食物上来时是冷的，服务员态度也不太好，我根本不喜欢这里。我不会再来了。']
Entity: 5月17日                           Category: DateTime         Confidence: 0.99
Entity: 服务员                             Category: PersonType       Confidence: 0.98
----------

-----Sentiment Analysis-----
The sentence to analyze: ['这家西餐厅已经很多年了，第一次来，感觉分量很大，太适合大口吃肉，大口喝酒的。']
Sentiment: positive
Confidence: {'positive': 0.92, 'neutral': 0.08, 'negative': 0.0}
----------


-----Key Phrases-----
The sentence to analyze:  ['这家西餐厅已经很多年了，第一次来，感觉分量很大，太适合大口吃肉，大口喝酒的。']
Key Phrases: ['这家西餐', '分', '大']
----------


-----Entities-----
The sentence to analyze:  ['这家西餐厅已经很多年了，第一次来，感觉分量很大，太适合大口吃肉，大口喝酒的。']
Entity: 西餐厅                             Category: Location         Confidence: 0.71
Entity: 第一次                             Category: Quantity         Confidence: 0.97
----------
----
